spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  datasource:
    master:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/customer_db
      username: admin
      password: admin123
    slave:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5433/customer_db
      username: admin
      password: admin123
  flyway:
    url: jdbc:postgresql://localhost:5432/customer_db
    user: admin
    password: admin123
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]
health:
  endpoint:
    url: "http://localhost:8080/actuator/prometheus"