service:
  name: fooddelivery-customer
  srvId: null
  appCatId: ""
  tier: HA
  team: ...
  productOwner:
    - ....
  techContacts:
    - Luk치코 M치코ka
business:
  requirement: "It is responsible for creating, fetching and managing partners, products and orders."
  SLA:
    availability: 99.99
    response: 500
technical:
  criticality: A
  documents:
infrastructure:
  infraProvider: ...
  platform: K8s
  apigw:
    name: other
    permalink: ...
  logging:
    name: Kibana
    permalink: ...
  monitoring:
    name: Grafana
    permalink: ...

  alerting:
    name: Sentry
    permalink: ...
