###
# CREATE ORDER
PUT {{host}}/api/v1/orders
Content-Type: application/json

{
  "productId": 268435460,
  "customerId": 1,
  "address": "Prague 11"
}


###
# Response: 201 CREATED
HTTP/1.1 201 CREATED
Content-Type: application/json

{
  "orderId": 1943897450219523,
  "status": "created"
}

###

# Response: 422 Unprocessable Entity
# - Product is not active
# - Product not exists
# - Customer not exists
HTTP/1.1 422 Conflict
Content-Type: application/json

{
  "message": "Customer with id 21 not exists."
}